### ISSUE TITLE
Software License

### ISSUE THREAD

**Issue by wtl420** [TheMinusWorld/Mayhem-Whereabouts#8]
We should decide on a license for the software.

I want to avoid the traditional ones like MIT or GPL and try something a bit different.

https://blog.licensezero.com/2019/09/11/patron-license-1.0.0.html might be a good contender, I really like the licenses https://writing.kemitchell.com/ has come up with, and would love to use one of them.

**Comment by wtl420** [comment]
I realize the patron license is specifically a license for people who have already become a patron, so it's a companion to an existing license.

https://licensezero.com/licenses/parity
I think this is a solid baseline copyleft license, it's fairly easy to read through and understand which makes it great. I really love the concept of "flipped form" https://flippedform.com/ licenses and want to stick with one of those.

**Comment by FunWithDespair** [comment]
I definitely like the idea of open source but requiring people to contribute their changes. Overall, that concept feels like potential eventual free outsourcing for QoL and feature additions, which I think is probably a net positive when it comes to long term usability down the line.

**Comment by wtl420** [comment]
Looked more into parity and it's a no-go since it has a weird clause for open source tools that requires anything made with the tool to be under the same license, which I don't really agree with.

https://indieopensource.com/public-private/public-licenses#AGPL-3.0

AGPL seems to do what I want, unfortunately it doesn't seem like there's a flipped form variant we can use but that's all right.

**Comment by wtl420** [comment]
Going to go with AGPL since there weren't any additional comments here. We can always change it if needed.
